import request from './request'

export const getOverview = () => request.get('/v1/dashboard/overview')
export const getYieldDashboard = () => request.get('/v1/dashboard/yield')

export const getOrders = (params = {}) => request.get('/v1/orders', { params })
export const createOrder = (data = {}) => request.post('/v1/orders', data)
export const releaseOrder = (orderNo, data = {}) => request.post(`/v1/orders/${orderNo}/release`, data)

export const getLots = (params = {}) => request.get('/v1/lots', { params })
export const trackInLot = (lotNo, data = {}) => request.post(`/v1/lots/${lotNo}/track-in`, data)
export const trackOutLot = (lotNo, data = {}) => request.post(`/v1/lots/${lotNo}/track-out`, data)
export const holdLot = (lotNo, data = {}) => request.post(`/v1/lots/${lotNo}/hold`, data)
export const releaseLot = (lotNo, data = {}) => request.post(`/v1/lots/${lotNo}/release`, data)
export const reworkLot = (lotNo, data = {}) => request.post(`/v1/lots/${lotNo}/rework`, data)
export const scrapLot = (lotNo, data = {}) => request.post(`/v1/lots/${lotNo}/scrap`, data)

export const getProducts = () => request.get('/v1/master/products')
export const getSites = () => request.get('/v1/master/sites')
export const getProductionLines = (params = {}) => request.get('/v1/master/production-lines', { params })
export const getShifts = (params = {}) => request.get('/v1/master/shifts', { params })
export const getProcessSteps = () => request.get('/v1/master/process-steps')
export const getEquipments = () => request.get('/v1/master/equipments')
export const getDefectCodes = () => request.get('/v1/master/defect-codes')
export const getRoutes = () => request.get('/v1/routes')
export const getBoms = () => request.get('/v1/boms')
export const getBomChangeRequests = (params = {}) => request.get('/v1/boms/change-requests', { params })
export const getBomEcoApprovals = (params = {}) => request.get('/v1/boms/eco-approvals', { params })
export const submitBomChange = (data = {}) => request.post('/v1/boms/change-requests', data)
export const decideBomEcoApproval = (taskNo, data = {}) => request.post(`/v1/boms/eco-approvals/${taskNo}/decision`, data)
export const reviewBomChange = (changeNo, data = {}) => request.post(`/v1/boms/change-requests/${changeNo}/review`, data)
export const publishBomChange = (changeNo, data = {}) => request.post(`/v1/boms/change-requests/${changeNo}/publish`, data)
export const getRecipes = (params = {}) => request.get('/v1/recipes', { params })
export const publishRecipe = (id) => request.post(`/v1/recipes/${id}/publish`)

export const getTraceLot = lotNo => request.get(`/v1/trace/lots/${lotNo}`)
export const getTraceSn = sn => request.get(`/v1/trace/sn/${sn}`)
export const searchTrace = (params = {}) => request.get('/v1/trace/search', { params })

export const getQualityInspections = (params = {}) => request.get('/v1/quality/inspections', { params })
export const getQualityExceptions = (params = {}) => request.get('/v1/quality/exceptions', { params })
export const getQualityMrbRecords = eventNo => request.get(`/v1/quality/exceptions/${eventNo}/mrb-records`)
export const getQualityMrbMinutes = mrbNo => request.get(`/v1/quality/mrb-records/${mrbNo}/minutes`)
export const createQualityMrbMinutes = (mrbNo, data = {}) => request.post(`/v1/quality/mrb-records/${mrbNo}/minutes`, data)
export const getQualityMrbApprovals = (params = {}) => request.get('/v1/quality/mrb-approvals', { params })
export const refreshQualityMrbApprovalSla = (data = {}) => request.post('/v1/quality/mrb-approvals/refresh-sla', data)
export const approveQualityMrbTask = (taskNo, data = {}) => request.post(`/v1/quality/mrb-approvals/${taskNo}/approve`, data)
export const rejectQualityMrbTask = (taskNo, data = {}) => request.post(`/v1/quality/mrb-approvals/${taskNo}/reject`, data)
export const reviewQualityException = (eventNo, data = {}) => request.post(`/v1/quality/exceptions/${eventNo}/mrb-review`, data)
export const closeQualityException = (eventNo, data = {}) => request.post(`/v1/quality/exceptions/${eventNo}/close`, data)
export const getEquipmentEvents = (params = {}) => request.get('/v1/equipment/events', { params })
export const createEquipmentEvent = (data = {}) => request.post('/v1/equipment/events', data)
export const closeEquipmentEvent = (eventNo, data = {}) => request.post(`/v1/equipment/events/${eventNo}/close`, data)
export const getEquipmentOee = (params = {}) => request.get('/v1/equipment/oee', { params })
export const getEquipmentStatusHistory = (params = {}) => request.get('/v1/equipment/status-history', { params })
export const reportEquipmentStatus = (data = {}) => request.post('/v1/equipment/status/report', data)
export const getEquipmentCycleSamples = (params = {}) => request.get('/v1/equipment/cycle-samples', { params })
export const reportEquipmentCycleSample = (data = {}) => request.post('/v1/equipment/cycle-samples/report', data)
export const getEquipmentStandardCycles = (params = {}) => request.get('/v1/equipment/standard-cycles', { params })
export const publishEquipmentStandardCycle = (data = {}) => request.post('/v1/equipment/standard-cycles', data)
export const getEquipmentGateways = (params = {}) => request.get('/v1/equipment/gateways', { params })
export const registerEquipmentGateway = (data = {}) => request.post('/v1/equipment/gateways', data)
export const heartbeatEquipmentGateway = (gatewayCode, data = {}) => request.post(`/v1/equipment/gateways/${gatewayCode}/heartbeat`, data)
export const checkEquipmentGatewayHealth = (gatewayCode, data = {}) => request.post(`/v1/equipment/gateways/${gatewayCode}/health-check`, data)
export const getEquipmentGatewayHealthChecks = (params = {}) => request.get('/v1/equipment/gateway-health-checks', { params })
export const getEquipmentGatewayMessages = (params = {}) => request.get('/v1/equipment/gateway-messages', { params })
export const getEquipmentGatewayDrivers = () => request.get('/v1/equipment/gateway-drivers')
export const getEquipmentParameterSamples = (params = {}) => request.get('/v1/equipment/parameters', { params })
export const reportEquipmentParameters = (data = {}) => request.post('/v1/equipment/parameters/report', data)
export const getEquipmentPmTasks = (params = {}) => request.get('/v1/equipment/pm-tasks', { params })
export const completeEquipmentPmTask = (taskNo, data = {}) => request.post(`/v1/equipment/pm-tasks/${taskNo}/complete`, data)
export const getEquipmentRecipeCommands = (params = {}) => request.get('/v1/equipment/recipe-downloads', { params })
export const downloadEquipmentRecipe = (data = {}) => request.post('/v1/equipment/recipe-downloads', data)
export const ingestEapMessage = (data = {}) => request.post('/v1/adapters/eap/messages', data)
export const importErpOrders = (data = {}) => request.post('/v1/adapters/erp/orders', data)
export const ingestQmsInspection = (data = {}) => request.post('/v1/adapters/qms/inspections', data)
export const checkWmsMaterialReadiness = (data = {}) => request.post('/v1/adapters/wms/material-readiness', data)
export const ingestWmsInventoryTransaction = (data = {}) => request.post('/v1/adapters/wms/inventory-transactions', data)
export const getMaterialBatches = () => request.get('/v1/material/batches')
export const receiveMaterial = (data = {}) => request.post('/v1/material/receive', data)
export const freezeMaterial = (batchNo, data = {}) => request.post(`/v1/material/batches/${batchNo}/freeze`, data)
export const unfreezeMaterial = (batchNo, data = {}) => request.post(`/v1/material/batches/${batchNo}/unfreeze`, data)
export const returnMaterial = (batchNo, data = {}) => request.post(`/v1/material/batches/${batchNo}/return`, data)
export const countMaterialInventory = (batchNo, data = {}) => request.post(`/v1/material/batches/${batchNo}/inventory-count`, data)
export const getMaterialInventoryTransactions = (params = {}) => request.get('/v1/material/inventory-transactions', { params })
export const getMaterialIncomingInspections = (params = {}) => request.get('/v1/material/incoming-inspections', { params })
export const createMaterialIncomingInspection = (batchNo, data = {}) => request.post(`/v1/material/batches/${batchNo}/incoming-inspection`, data)
export const getMaterialConsumptions = (params = {}) => request.get('/v1/material/consumptions', { params })
export const getMaterialSupplierPerformance = () => request.get('/v1/material/suppliers/performance')
export const getMaterialSupplierTrends = (params = {}) => request.get('/v1/material/suppliers/trends', { params })
export const getMaterialSuppliers = () => request.get('/v1/material/suppliers')
export const evaluateMaterialSupplierQualification = (supplierCode, data = {}) => request.post(`/v1/material/suppliers/${supplierCode}/qualification/evaluate`, data)
export const getSupplierQualificationReviews = (params = {}) => request.get('/v1/material/suppliers/qualification-reviews', { params })
export const createSupplierQualificationReview = (supplierCode, data = {}) => request.post(`/v1/material/suppliers/${supplierCode}/qualification-reviews`, data)
export const decideSupplierQualificationReview = (taskNo, data = {}) => request.post(`/v1/material/suppliers/qualification-reviews/${taskNo}/decision`, data)
export const getSupplierCorrectiveActions = (params = {}) => request.get('/v1/material/suppliers/corrective-actions', { params })
export const createSupplierCorrectiveAction = (data = {}) => request.post('/v1/material/suppliers/corrective-actions', data)
export const closeSupplierCorrectiveAction = (actionNo, data = {}) => request.post(`/v1/material/suppliers/corrective-actions/${actionNo}/close`, data)
export const getMaterialLocations = () => request.get('/v1/material/locations')
export const getMaterialLocationTasks = (params = {}) => request.get('/v1/material/location-tasks', { params })
export const createMaterialLocationTask = (data = {}) => request.post('/v1/material/location-tasks', data)
export const assignMaterialLocationTask = (taskNo, data = {}) => request.post(`/v1/material/location-tasks/${taskNo}/assign`, data)
export const completeMaterialLocationTask = (taskNo, data = {}) => request.post(`/v1/material/location-tasks/${taskNo}/complete`, data)
export const cancelMaterialLocationTask = (taskNo, data = {}) => request.post(`/v1/material/location-tasks/${taskNo}/cancel`, data)
export const getCarriers = () => request.get('/v1/carriers')

export const createYieldReport = (data = {}) => request.post('/v1/ai/reports/yield', data)
export const analyzeEquipment = (data = {}) => request.post('/v1/ai/equipment/analyze', data)
export const askKnowledgeBase = (data = {}) => request.post('/v1/ai/kb/ask', data)
export const getAiModelConfigs = () => request.get('/v1/ai/model-configs')
export const getAiReportRecords = (params = {}) => request.get('/v1/ai/report-records', { params })
export const getKnowledgeDocuments = () => request.get('/v1/ai/kb/documents')
export const importKnowledgeDocument = (data = {}) => request.post('/v1/ai/kb/import', data)
export const getKnowledgeIndexJobs = (params = {}) => request.get('/v1/ai/kb/index-jobs', { params })
export const createKnowledgeIndexJob = (data = {}) => request.post('/v1/ai/kb/index-jobs', data)

export const getSystemSummary = () => request.get('/v1/system/summary')
export const getSystemUsers = () => request.get('/v1/system/users')
export const getAuditLogs = (params = {}) => request.get('/v1/system/audit-logs', { params })
export const getPermissionChangeRequests = (params = {}) => request.get('/v1/system/permission-change-requests', { params })
export const createPermissionChangeRequest = (data = {}) => request.post('/v1/system/permission-change-requests', data)
export const reviewPermissionChangeRequest = (changeNo, data = {}) => request.post(`/v1/system/permission-change-requests/${changeNo}/review`, data)
export const reloadPermissions = () => request.post('/v1/system/permissions/reload')
